name: Build

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - master

jobs:
  phpmake:
    name: "Linux: PHP Make v${{ matrix.php }}"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        php:
          - '7.3'
          - '7.4'

        include:
          - php: '7.3'
          - php: '7.4'
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: gmp, psr, zip

      - name: Checkout code
          uses: actions/checkout@v2-beta
          with:
            fetch-depth: 5

      - name: Run default target
        run: make -f php.mk
