name: Build

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - master

jobs:
  phpmake:
    name: "PHP Make ${{ matrix.osname }}"
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        name:
          - ubuntu-16.04
          - macOS-latest

        include:
          - name: ubuntu-16.04
            os: ubuntu-16.04
            osname: Linux
            php: 7.3

          - name: macOS-latest
            os: macOS-latest
            osname: macOS
            php: 7.4
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: gmp, psr, zip

      - name: Checkout code
        uses: actions/checkout@v2-beta
        with:
          fetch-depth: 5

      - name: Run default target
        run: make -f php.mk
