name: Build

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - master

jobs:
  phpmake:
    strategy:
      fail-fast: false

      matrix:
        options:
          - name: Ubuntu
          os: ubuntu-18.04
          osname: Linux
          php: 7.3
          - name: macOS
          os: macOS-latest
          osname: macOS
          php: 7.4

    name: "PHP Make ${{ matrix.osname }}"
    runs-on: ${{matrix.options.os}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: gmp, psr, zip
          tools: phpize, php-config

      - name: Run default target
        run: make -f php.mk

      - name: Check libtool
        run: |
          ls -lah /usr/share/libtool
          ls -lah /usr/share/libtool/build-aux
          libtool --version
