name: Build

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      COMPOSER_NO_INTERACTION: 1

    strategy:
      fail-fast: false

      matrix:
        php-version:
          - '7.4'
          - '8.0'

    name: "Run with PHP ${{ matrix.php-version }}"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: psr, zip
          tools: composer:v2

      - name: Get Composer Cache Dev
        id: composer-cache-dev
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache-dev.outputs.dir }}
          key: ${{ runner.os }}-composer-dev-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-composer-dev-

      - name: Composer Install Dev
        run: |
          composer install --prefer-dist --no-interaction --no-ansi --no-suggest --no-scripts

      - name: Run PHPCS for the codestyle
        run: |
          make phpcs
