name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Parse CHANGELOG for Release Notes
        id: release
        run: |
          echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
          echo ::set-output name=RELEASE_NOTES::$(.github/release-notes.sh CHANGELOG.md)

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: v${{ steps.release.outputs.VERSION }}
          tag: ${{ steps.release.outputs.VERSION }}
          body: ${{ steps.release.outputs.RELEASE_NOTES }}
          allowUpdates: true
